#!/bin/bash
# 18 · The two notifications that never turn off
#
# Run INSIDE the VM:   bash 18-persistent-notifications.sh
#
# SYMPTOM A — "Update System" reappears on every boot even when everything is up to date.
#   omarchy-provision-first-run only marks first-run as done if NO step
#   fails. Here enable-user-units.sh always failed, for TWO reasons:
#     1. The six .service files were never installed in /usr/lib/systemd/user/.
#        Upstream ships them with the omarchy-settings package, which doesn't exist
#        for ARM (docs/file-layout.md: "systemd/user/*.service → /usr/lib/systemd/user/").
#     2. Those .service files invoke /usr/bin/omarchy-*, and this image had the
#        commands in /usr/local/bin.
#   Since it never gets marked, first-run repeats on every login and wifi.sh relaunches the notification.
#
# SYMPTOM B — "Linux kernel has been updated. Reboot?" always shows up.
#   omarchy-update-restart looks for a vmlinuz inside /usr/lib/modules/<ver>/
#   owned by a package. On Arch x86_64 the linux package installs it; on
#   Arch Linux ARM, linux-aarch64 leaves the image in /boot/Image and never creates that
#   vmlinuz. The loop finds nothing, kernel_updated stays true, and it asks to
#   reboot on every update. Rebooting doesn't help: the condition can never
#   become false.
set -uo pipefail
echo "==> A. omarchy commands to /usr/bin (where the tree expects them)"
n=0
for f in /usr/share/omarchy/bin/*; do
  [ -f "$f" ] || continue
  sudo ln -sfn "$f" "/usr/bin/$(basename "$f")" && n=$((n+1))
done
echo "   $n commands linked into /usr/bin"

echo "==> A2. user units where systemd looks for them"
# This was the missing step: without the .service files installed, enable-user-units.sh
# can't work no matter how many paths get fixed.
if [ -d /usr/share/omarchy/default/systemd/user ]; then
  sudo install -d /usr/lib/systemd/user
  sudo cp -a /usr/share/omarchy/default/systemd/user/. /usr/lib/systemd/user/
  echo "   $(ls /usr/lib/systemd/user/*.service 2>/dev/null | wc -l) units available"
else
  echo "   can't find /usr/share/omarchy/default/systemd/user"
fi

echo "==> B. wrapper for the kernel notification"
sudo install -Dm755 /dev/stdin /usr/local/bin/omarchy-update-restart <<'KRN'
#!/bin/bash
if [ -z "${OMARCHY_SKIP_KERNEL_CHECK:-}" ]; then
  # modules.dep is generated by depmod and doesn't belong to any package. modules.builtin
  # is shipped by linux-aarch64, so it works to check whether the running kernel's
  # module directory belongs to the installed package.
  pkg=$(pacman -Qoq /usr/lib/modules/"$(uname -r)"/modules.builtin 2>/dev/null \
        || pacman -Qoq /usr/lib/modules/"$(uname -r)"/modules.order 2>/dev/null || true)
  [ -n "$pkg" ] && export OMARCHY_KERNEL_CURRENT=1
fi
REAL=/usr/bin/omarchy-update-restart
[ -x "$REAL" ] || exit 0
if [ -n "${OMARCHY_KERNEL_CURRENT:-}" ]; then
  sed 's#^kernel_updated=true$#kernel_updated=false#' "$REAL" | bash -s -- "$@"
else
  exec "$REAL" "$@"
fi
KRN
echo "   /usr/local/bin/omarchy-update-restart"

echo "==> C. complete first-run so it stops repeating"
bash /usr/share/omarchy/install/user/first-run/enable-user-units.sh \
  && echo "   enable-user-units.sh: succeeded this time" \
  || echo "   still failing: check 'systemctl --user status' for the six units"
omarchy-provision-first-run --force 2>&1 | tail -3

echo "==> check"
printf "   units installed:     %s\n" "$(ls /usr/lib/systemd/user/*.service 2>/dev/null | wc -l)"
printf "   first-run marked:    %s\n" "$(omarchy-done check first-run-user && echo yes || echo NO)"
printf "   running kernel:      %s\n" "$(uname -r)"
printf "   owned by:            %s\n" "$(pacman -Qoq /usr/lib/modules/"$(uname -r)"/modules.builtin 2>/dev/null || echo "(nobody)")"
echo "   omarchy-update-restart should no longer ask for a reboot from now on."
